# Uncomment the next line to define a global platform for your project
  platform :ios, '12.0'

target 'ImageMachine' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImageMachine
    pod 'QRCodeReader.swift'
    pod 'TLPhotoPicker'
    pod 'IHKeyboardAvoiding'
    pod 'AFDateHelper', '~> 4.2.2'
    pod 'SKPhotoBrowser'

  target 'ImageMachineTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ImageMachineUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
